# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8205d71bff9a39514bdd903aaad1d1afb2f147c23c07b78e696a48762290f30e15ac8ccae6b3d5a2ee202d61ef150d40f560e9c7f960756218c62448131addc8

test:
  secret_key_base: bf70bbfb05ab0bea372f8550ee44ae00d172bb645f234872baf37b14f83e6a7b5469dcb2511b64fef6d3aac2ba7dfbcf3b06d863c970fd1983ec3bab59134e31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
